# Generated by Django 5.1.7 on 2025-05-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_homepage', models.BooleanField(default=False)),
                ('layout', models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='grid', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=100)),
                ('ordering', models.IntegerField(default=0)),
            ],
        ),
    ]
