# Generated by Django 5.1.7 on 2025-05-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningsite', '0002_alter_category_options_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(),
        ),
    ]
