# Generated by Django 5.1.7 on 2025-05-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningsite', '0005_alter_lesson_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_homepage',
        ),
    ]
