# Generated by Django 5.1.7 on 2025-05-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningsite', '0007_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories'),
        ),
    ]
