# Generated by Django 5.1.7 on 2025-06-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningsite', '0009_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('theory', 'Lý thuyết'), ('exercise', 'Bài tập')], default='theory', max_length=10),
        ),
    ]
